/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.examengrupal2doparcial;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo Velasquez
 */
public class Actualizar_credito extends javax.swing.JFrame {
     
    public void setDatos(int id, java.sql.Date fechaCredito, BigDecimal credito,
        java.sql.Date fechaDebito, BigDecimal debito, BigDecimal saldo) {
        txt_id.setText(String.valueOf(id));
        txtf_fechacredito.setText(String.valueOf(fechaCredito));
        txt_credito.setText(String.valueOf(credito));
        txt_fechadebito.setText(String.valueOf(fechaDebito));
        txt_debito.setText(String.valueOf(debito));
        txt_saldo.setText(String.valueOf(saldo));
    }
       
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Actualizar_credito.class.getName());

    /**
     * Creates new form Actualizar_credito
     */
    public Actualizar_credito() {
        initComponents();
        this.setLocationRelativeTo(this);
        setDefaultCloseOperation(this.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtf_fechacredito = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_credito = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_fechadebito = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_debito = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_saldo = new javax.swing.JTextField();
        Actualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Actualizar Datos Credito");

        jLabel2.setText("Cliente ID:");

        jLabel3.setText("Fecha Credito:");

        jLabel4.setText("Credito");

        jLabel5.setText("Fecha debito:");

        jLabel6.setText("debito");

        jLabel7.setText("Saldo");

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(this::ActualizarActionPerformed);

        jButton2.setText("Limpiar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_id)
                            .addComponent(txtf_fechacredito)
                            .addComponent(txt_credito)
                            .addComponent(txt_fechadebito)
                            .addComponent(txt_debito)
                            .addComponent(txt_saldo, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Actualizar)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtf_fechacredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_credito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_fechadebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_debito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Actualizar)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    txt_id.setText("");
    txtf_fechacredito.setText("");
    txt_credito.setText("");
    txt_fechadebito.setText("");
    txt_debito.setText("");
    txt_saldo.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
          try {
       
        if (txt_id.getText().trim().isEmpty() ||
            txtf_fechacredito.getText().trim().isEmpty() ||
            txt_credito.getText().trim().isEmpty() ||
            txt_fechadebito.getText().trim().isEmpty() ||
            txt_debito.getText().trim().isEmpty() ||
            txt_saldo.getText().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }

        
        int clienteId = Integer.parseInt(txt_id.getText().trim());
        java.sql.Date fechaCredito = java.sql.Date.valueOf(txtf_fechacredito.getText().trim());
        BigDecimal montoCredito = new BigDecimal(txt_credito.getText().trim());
        java.sql.Date fechaDebito = java.sql.Date.valueOf(txt_fechadebito.getText().trim());
        BigDecimal montoDebito = new BigDecimal(txt_debito.getText().trim());
        BigDecimal saldo = new BigDecimal(txt_saldo.getText().trim());

        
        ClsConexion miConexion = new ClsConexion();
        Connection conexion = miConexion.conectar();
        Statement st = conexion.createStatement();

      
        String sql = "UPDATE Creditos SET " +
                     "FechaCredito = '" + fechaCredito + "', " +
                     "MontoCredito = " + montoCredito + ", " +
                     "FechaDebito = '" + fechaDebito + "', " +
                     "MontoDebito = " + montoDebito + ", " +
                     "Saldo = " + saldo + " " +
                     "WHERE ClienteID = " + clienteId;

        int filas = st.executeUpdate(sql);

        JOptionPane.showMessageDialog(this, 
            filas > 0 ? "Crédito actualizado correctamente." : "No se pudo actualizar el crédito.");

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error en la base de datos: " + ex.getMessage());
    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Actualizar_credito().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_credito;
    private javax.swing.JTextField txt_debito;
    private javax.swing.JTextField txt_fechadebito;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_saldo;
    private javax.swing.JTextField txtf_fechacredito;
    // End of variables declaration//GEN-END:variables
}
