/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.examengrupal2doparcial;


import com.mycompany.examengrupal2doparcial.UtilidadesGUI.ListarCampos;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author David Rubio
 */
public class FrmNuevaCompra extends javax.swing.JInternalFrame {

    
    public JComboBox<String> getComboTienda() {
        return cmbtienda;
    }
    
private java.sql.Date validarFecha(String valor, String nombreCampo) {
   
    System.out.println("Valor recibido en " + nombreCampo + ": [" + valor + "]");
    try {
        java.time.LocalDate fecha = java.time.LocalDate.parse(
            valor.trim(),
            java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd")
        );
        return java.sql.Date.valueOf(fecha);
    } catch (java.time.format.DateTimeParseException e) {
        throw new IllegalArgumentException(
            nombreCampo + " debe estar en formato YYYY-MM-DD y ser una fecha válida"
        );
    }
}

    private BigDecimal validarDecimal(String valor, String nombreCampo) {
        try {
            return new BigDecimal(valor);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(nombreCampo + " debe ser un número decimal");
        }
    }
    public FrmNuevaCompra() {
        initComponents();
        
        cmbestado.addItem("Nuevo");
        cmbestado.addItem("Semiusado");
        cmbestado.addItem("Usado");
        cmbestado.addItem("Viejo");
        
        cmbvia.addItem("Null");
        cmbformato.addItem("Null");
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RB_casillero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txtporcentajecomision = new javax.swing.JTextField();
        cmbestado = new javax.swing.JComboBox<>();
        txtcliente = new javax.swing.JTextField();
        rbotro = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        cmbvia = new javax.swing.JComboBox<>();
        txtimpuesto = new javax.swing.JTextField();
        txtdescuento = new javax.swing.JTextField();
        txtenvio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtobservaciones = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txttasa = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnagregar2 = new javax.swing.JButton();
        BTN_Eliminar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtflete = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtcosto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtotrosgastos = new javax.swing.JTextField();
        txtpvsc = new javax.swing.JTextField();
        txtpvcc = new javax.swing.JTextField();
        txtgdc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LBL_GDC = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtarticulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtporcentajegdc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtgcc = new javax.swing.JTextField();
        cmbtienda = new javax.swing.JComboBox<>();
        txtporcentajegcc = new javax.swing.JTextField();
        txtcomision = new javax.swing.JTextField();
        txtorden = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txttracking = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbformato = new javax.swing.JComboBox<>();
        rb504 = new javax.swing.JRadioButton();
        txtfecharecepcion = new javax.swing.JFormattedTextField();
        txtfechadespacho = new javax.swing.JFormattedTextField();
        txtfecha = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        txtlinkArticulo = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtaplicaCCCE = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtCCCE = new javax.swing.JTextField();
        Añadir_tienda = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jLabel28.setText("Fecha de Recepcion:");

        cmbestado.addActionListener(this::cmbestadoActionPerformed);

        RB_casillero.add(rbotro);
        rbotro.setText("Otro");
        rbotro.addActionListener(this::rbotroActionPerformed);

        jLabel9.setText("Precio Compra:");

        jLabel29.setText("Via de Despacho:");

        jLabel10.setText("Descuento:");

        jLabel30.setText("Fecha de Despacho:");

        jLabel11.setText("Envio:");

        jLabel31.setText("Observaciones:");

        txtimpuesto.addActionListener(this::txtimpuestoActionPerformed);

        jLabel12.setText("Impuesto:");

        jLabel13.setText("Total USD:");

        txtobservaciones.setColumns(20);
        txtobservaciones.setRows(5);
        jScrollPane1.setViewportView(txtobservaciones);

        jLabel14.setText("Tasa:");

        btnagregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Guardar.png"))); // NOI18N
        btnagregar2.addActionListener(this::btnagregar2ActionPerformed);

        BTN_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Borrar.png"))); // NOI18N
        BTN_Eliminar.addActionListener(this::BTN_EliminarActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnagregar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTN_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnagregar2)
                .addGap(59, 59, 59)
                .addComponent(BTN_Eliminar)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jLabel15.setText("Flete HNL:");

        jLabel16.setText("Costo HNL:");

        jLabel17.setText("Otros Gastos HNL:");

        jLabel18.setText("PVsC:");

        jLabel19.setText("PVcC:");

        jLabel20.setText("GdC:");

        txtpvsc.addActionListener(this::txtpvscActionPerformed);

        txtpvcc.addActionListener(this::txtpvccActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("NUEVA COMPRA");

        LBL_GDC.setText("%GdC:");

        jLabel2.setText("Articulo:");

        txtarticulo.addActionListener(this::txtarticuloActionPerformed);

        jLabel3.setText("No. Orden:");

        jLabel4.setText("Tracking:");

        jLabel22.setText("GcC:");

        jLabel23.setText("%GcC:");

        jLabel24.setText("Comision:");

        jLabel25.setText("%Comision:");

        jLabel5.setText("Fecha Compra:");

        jLabel6.setText("Tienda:");

        jLabel26.setText("Estado:");

        jLabel27.setText("Cliente:");

        jLabel7.setText("Formato Compra:");

        jLabel8.setText("Casillero:");

        RB_casillero.add(rb504);
        rb504.setText("504Express");

        try {
            txtfecharecepcion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfecharecepcion.addActionListener(this::txtfecharecepcionActionPerformed);

        try {
            txtfechadespacho.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfecha.addActionListener(this::txtfechaActionPerformed);

        jLabel21.setText("Link");

        txtlinkArticulo.setText("NULL");

        jLabel32.setText("AplicaCCCE");

        jLabel33.setText("CCCE");

        Añadir_tienda.setText("Añadir Tienda");
        Añadir_tienda.addActionListener(this::Añadir_tiendaActionPerformed);

        jButton1.setText("Eliminar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbformato, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(txttasa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtpvcc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtotrosgastos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel32))
                                .addGap(18, 18, 18)
                                .addComponent(txtporcentajegcc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb504, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbotro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtenvio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtpvsc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtimpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtgdc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcomision, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(cmbvia, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfechadespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfecharecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(LBL_GDC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtporcentajegdc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtporcentajecomision, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtlinkArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(250, 250, 250)
                                .addComponent(txtgcc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtorden, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbtienda, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttracking, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Añadir_tienda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtflete, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(txtaplicaCCCE, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCCCE, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(527, 527, 527)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txttracking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(cmbtienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Añadir_tienda)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbformato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(rb504)
                            .addComponent(rbotro))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtenvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtimpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtflete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(txttasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtotrosgastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtpvcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(txtpvsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txtgdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_GDC)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(txtporcentajegdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtporcentajegcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcomision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtlinkArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(txtaplicaCCCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(txtCCCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addComponent(txtporcentajecomision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecharecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(jLabel30)
                        .addComponent(jLabel31)
                        .addComponent(cmbvia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfechadespacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtcliente.getAccessibleContext().setAccessibleName("Cliente");
        txtarticulo.getAccessibleContext().setAccessibleName("Articulo");
        txtorden.getAccessibleContext().setAccessibleName("No. Orden:");
        txttracking.getAccessibleContext().setAccessibleName("Tracking");
        txtfechadespacho.getAccessibleContext().setAccessibleName("Fecha Despacho");
        txtfecha.getAccessibleContext().setAccessibleName("FECHA Compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtarticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtarticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtarticuloActionPerformed

    private void txtpvccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpvccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpvccActionPerformed

    private void txtpvscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpvscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpvscActionPerformed

    private void txtimpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimpuestoActionPerformed

    private void rbotroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbotroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbotroActionPerformed

    private void cmbestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbestadoActionPerformed

    private void btnagregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar2ActionPerformed
          JTextField[] campos = {txtporcentajegdc, txtarticulo, txtcliente, txtcomision, txtcosto,
            txtdescuento, txtenvio, txtfecha, txtfechadespacho, txtfecharecepcion,
            txtflete, txtgcc, txtgdc, txtimpuesto, txtorden, txtotrosgastos,
            txtporcentajecomision, txtporcentajegcc, txtprecio, txtpvcc, txtpvsc,
            txttasa, txttotal, txttracking};
          
          
JComboBox<?>[] combos = {
    cmbtienda, cmbestado, cmbformato, cmbvia 
};

        StringBuilder mensaje = new StringBuilder("Los siguientes campos están vacíos:\n");
        for (JTextField campo : campos) {
            if (campo.getText().trim().isEmpty()) {
                String nombreCampo = campo.getAccessibleContext().getAccessibleName();
                mensaje.append("- ").append(nombreCampo).append("\n");
            }
        }
        
        for (JComboBox<?> combo : combos) {
    if (combo.getSelectedItem() == null || combo.getSelectedIndex() == -1) {
        String nombreCampo = combo.getAccessibleContext().getAccessibleName();
        mensaje.append("- ").append(nombreCampo).append("\n");
    }
}
        
        if (mensaje.length() > "Los siguientes campos están vacíos:\n".length()) {
            JOptionPane.showMessageDialog(null, mensaje.toString());
            return;
        }

        try {
            int clienteId = Integer.parseInt(txtcliente.getText().trim());
            int aplicaCCCE = Integer.parseInt(txtaplicaCCCE.getText().trim());
            if (aplicaCCCE != 0 && aplicaCCCE != 1) {
                throw new IllegalArgumentException("AplicaCCCE debe ser 0 o 1");
            }

            java.sql.Date fechaRecepcion = validarFecha(txtfecharecepcion.getText().trim(), "FechaRecepcion");
            java.sql.Date fechaCompra    = validarFecha(txtfecha.getText().trim(), "FechaCompra");
            java.sql.Date fechaDespacho  = validarFecha(txtfechadespacho.getText().trim(), "FechaDespacho");

            BigDecimal precioCompra       = validarDecimal(txtprecio.getText().trim(), "PrecioCompra");
            BigDecimal descuento          = validarDecimal(txtdescuento.getText().trim(), "Descuento");
            BigDecimal envio              = validarDecimal(txtenvio.getText().trim(), "Envio");
            BigDecimal impuesto           = validarDecimal(txtimpuesto.getText().trim(), "Impuesto");
            BigDecimal totalUSD           = validarDecimal(txttotal.getText().trim(), "TotalUSD");
            BigDecimal tasa               = validarDecimal(txttasa.getText().trim(), "Tasa");
            BigDecimal fleteHNL           = validarDecimal(txtflete.getText().trim(), "FleteHNL");
            BigDecimal otrosGastosHNL     = validarDecimal(txtotrosgastos.getText().trim(), "OtrosGastosHNL");
            BigDecimal costoHNL           = validarDecimal(txtcosto.getText().trim(), "CostoHNL");
            BigDecimal pvsc               = validarDecimal(txtpvsc.getText().trim(), "PVsC");
            BigDecimal pvcc               = validarDecimal(txtpvcc.getText().trim(), "PVcC");
            BigDecimal gsc                = validarDecimal(txtgdc.getText().trim(), "GsC");
            BigDecimal porcentajeGsc      = validarDecimal(txtporcentajegdc.getText().trim(), "PorcentajeGsC");
            BigDecimal gcc                = validarDecimal(txtgcc.getText().trim(), "GcC");
            BigDecimal porcentajeGcc      = validarDecimal(txtporcentajegcc.getText().trim(), "PorcentajeGcC");
            BigDecimal comision           = validarDecimal(txtcomision.getText().trim(), "Comision");
            BigDecimal porcentajeComision = validarDecimal(txtporcentajecomision.getText().trim(), "PorcentajeComision");

            ClsConexion miConexion = new ClsConexion();
            Connection conexion = miConexion.conectar();
            InsertHelper helper = new InsertHelper();

            java.util.List<String> columnas = java.util.List.of(
                "Nombre", "Estado", "ClienteID", "NoOrden", "Tracking",
                "FechaRecepcion", "FechaCompra", "ViaDespacho", "Tienda", "FechaDespacho",
                "Observaciones", "Casillero", "LinkArticulo",
                "PrecioCompra", "Descuento", "Envio", "Impuesto", "TotalUSD", "Tasa",
                "FleteHNL", "OtrosGastosHNL", "CostoHNL",
                "PVsC", "PVcC",
                "AplicaCCCE", "CCCE",
                "GsC", "PorcentajeGsC", "GcC", "PorcentajeGcC",
                "Comision", "PorcentajeComision"
            );

            java.util.List<Object> valores = java.util.List.of(
                txtarticulo.getText(),
                cmbestado.getSelectedItem().toString(),
                clienteId,
                txtorden.getText(),
                txttracking.getText(),
                fechaRecepcion,
                fechaCompra,
                cmbvia.getSelectedItem().toString(),
                cmbtienda.getSelectedItem().toString(),
                fechaDespacho,
                txtobservaciones.getText(),
                rb504.isSelected() ? "504Express" : "Otro",
                txtlinkArticulo.getText().isEmpty() ? null : txtlinkArticulo.getText(),
                precioCompra, descuento, envio, impuesto, totalUSD, tasa,
                fleteHNL, otrosGastosHNL, costoHNL,
                pvsc, pvcc,
                aplicaCCCE, txtCCCE.getText().isEmpty() ? null : txtCCCE.getText(),
                gsc, porcentajeGsc, gcc, porcentajeGcc,
                comision, porcentajeComision
            );

            boolean ok = helper.insertar(conexion, "Articulos", columnas, valores);
            JOptionPane.showMessageDialog(null, ok ? "Registro insertado correctamente." : "Error al insertar registro.");

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error de formato numérico: " + ex.getMessage());
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, "Validación fallida: " + ex.getMessage());
        } catch (SQLException ex) {
            System.getLogger(FrmNuevaCompra.class.getName())
                  .log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + ex.getMessage());
        }
   
      
        
    }//GEN-LAST:event_btnagregar2ActionPerformed

    private void BTN_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EliminarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
        null,
        "¿Desea eliminar todos los campos?",
        "Confirmación",
        JOptionPane.YES_NO_OPTION
    );

    
    if (opcion == JOptionPane.YES_OPTION) {
        
        
        txtCCCE.setText("");
        txtaplicaCCCE.setText("");
        txtarticulo.setText("");
        txtcliente.setText("");
        txtcomision.setText("");
        txtcosto.setText("");
        txtdescuento.setText("");
        txtenvio.setText("");
        txtfecha.setText("");          
        txtfechadespacho.setText("");  
        txtfecharecepcion.setText(""); 
        txtflete.setText("");
        txtgcc.setText("");
        txtgdc.setText("");
        txtimpuesto.setText("");
        txtlinkArticulo.setText("");
        txtorden.setText("");
        txtotrosgastos.setText("");
        txtporcentajecomision.setText("");
        txtporcentajegcc.setText("");
        txtporcentajegdc.setText("");
        txtprecio.setText("");
        txtpvcc.setText("");
        txtpvsc.setText("");
        txttasa.setText("");
        txttotal.setText("");
        txttracking.setText("");

        
        cmbtienda.setSelectedIndex(-1);
        cmbestado.setSelectedIndex(-1);
        cmbformato.setSelectedIndex(-1);
        cmbvia.setSelectedIndex(-1);

        
        rb504.setSelected(false);
        rbotro.setSelected(false);
     
        txtobservaciones.setText("");

        
        JOptionPane.showMessageDialog(null, "Todos los campos han sido limpiados correctamente.");
    }
    }//GEN-LAST:event_BTN_EliminarActionPerformed

    private void txtfecharecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfecharecepcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfecharecepcionActionPerformed

    private void Añadir_tiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Añadir_tiendaActionPerformed
        
        Nueva_tienda frTienda = new Nueva_tienda(this);
        frTienda.setVisible(true);
        
    }//GEN-LAST:event_Añadir_tiendaActionPerformed

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir_tienda;
    private javax.swing.JButton BTN_Eliminar;
    private javax.swing.JLabel LBL_GDC;
    private javax.swing.ButtonGroup RB_casillero;
    private javax.swing.JButton btnagregar2;
    private javax.swing.JComboBox<String> cmbestado;
    private javax.swing.JComboBox<String> cmbformato;
    private javax.swing.JComboBox<String> cmbtienda;
    private javax.swing.JComboBox<String> cmbvia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb504;
    private javax.swing.JRadioButton rbotro;
    private javax.swing.JTextField txtCCCE;
    private javax.swing.JTextField txtaplicaCCCE;
    private javax.swing.JTextField txtarticulo;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcomision;
    private javax.swing.JTextField txtcosto;
    private javax.swing.JTextField txtdescuento;
    private javax.swing.JTextField txtenvio;
    private javax.swing.JFormattedTextField txtfecha;
    private javax.swing.JFormattedTextField txtfechadespacho;
    private javax.swing.JFormattedTextField txtfecharecepcion;
    private javax.swing.JTextField txtflete;
    private javax.swing.JTextField txtgcc;
    private javax.swing.JTextField txtgdc;
    private javax.swing.JTextField txtimpuesto;
    private javax.swing.JTextField txtlinkArticulo;
    private javax.swing.JTextArea txtobservaciones;
    private javax.swing.JTextField txtorden;
    private javax.swing.JTextField txtotrosgastos;
    private javax.swing.JTextField txtporcentajecomision;
    private javax.swing.JTextField txtporcentajegcc;
    private javax.swing.JTextField txtporcentajegdc;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtpvcc;
    private javax.swing.JTextField txtpvsc;
    private javax.swing.JTextField txttasa;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttracking;
    // End of variables declaration//GEN-END:variables
}
