/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.examengrupal2doparcial;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;

/**
 *
 * @author David Rubio
 */
public class FrmPaginaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPaginaPrincipal.class.getName());

    /**
     * Creates new form FrmEmpleados
     */
    public FrmPaginaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelFormularios = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnMantenimiento = new javax.swing.JMenu();
        MnCompras = new javax.swing.JMenu();
        MnNuevaCompra = new javax.swing.JMenu();
        MnPosibleCompra = new javax.swing.JMenu();
        MnClientes = new javax.swing.JMenu();
        MnCreditos = new javax.swing.JMenu();
        MnImpuestos = new javax.swing.JMenu();
        MnReportes = new javax.swing.JMenu();
        MnExportar = new javax.swing.JMenu();
        MnComprobante = new javax.swing.JMenu();
        MnTiendas = new javax.swing.JMenu();
        MnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de Registro TrackBuy");

        javax.swing.GroupLayout PanelFormulariosLayout = new javax.swing.GroupLayout(PanelFormularios);
        PanelFormularios.setLayout(PanelFormulariosLayout);
        PanelFormulariosLayout.setHorizontalGroup(
            PanelFormulariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelFormulariosLayout.setVerticalGroup(
            PanelFormulariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        jMenu1.setText("Compras");
        jMenuBar1.add(jMenu1);

        MnMantenimiento.setText("Mantenimientos");
        MnMantenimiento.addActionListener(this::MnMantenimientoActionPerformed);

        MnCompras.setText("Compras");
        MnCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnComprasMouseClicked(evt);
            }
        });
        MnCompras.addActionListener(this::MnComprasActionPerformed);
        MnMantenimiento.add(MnCompras);

        MnNuevaCompra.setText("Nueva Compra");
        MnNuevaCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnNuevaCompraMouseClicked(evt);
            }
        });
        MnMantenimiento.add(MnNuevaCompra);

        MnPosibleCompra.setText("Posible Compra");
        MnPosibleCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnPosibleCompraMouseClicked(evt);
            }
        });
        MnMantenimiento.add(MnPosibleCompra);

        MnClientes.setText("Clientes");
        MnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnClientesMouseClicked(evt);
            }
        });
        MnMantenimiento.add(MnClientes);

        MnCreditos.setText("Creditos");
        MnCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnCreditosMouseClicked(evt);
            }
        });
        MnMantenimiento.add(MnCreditos);

        MnImpuestos.setText("Impuestos");
        MnImpuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnImpuestosMouseClicked(evt);
            }
        });
        MnMantenimiento.add(MnImpuestos);

        jMenuBar1.add(MnMantenimiento);

        MnReportes.setText("Reportes");

        MnExportar.setText("Exportar a Excel");
        MnReportes.add(MnExportar);

        MnComprobante.setText("Comprobante");
        MnReportes.add(MnComprobante);

        MnTiendas.setText("Tiendas Mas Usadas");
        MnReportes.add(MnTiendas);

        jMenuBar1.add(MnReportes);

        MnSalir.setText("Salir");
        jMenuBar1.add(MnSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(1004, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFormularios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelFormularios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnMantenimientoActionPerformed

    private void MnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnComprasActionPerformed
        
    }//GEN-LAST:event_MnComprasActionPerformed

    private void MnComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnComprasMouseClicked
        PanelFormularios.removeAll();
        PanelFormularios.repaint();                
        
        FrmCompra frmc = new FrmCompra();
        PanelFormularios.add(frmc);
        frmc.setVisible(true);
    }//GEN-LAST:event_MnComprasMouseClicked

    private void MnNuevaCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnNuevaCompraMouseClicked
        PanelFormularios.removeAll();
    PanelFormularios.repaint(); 

    FrmNuevaCompra frmnc = new FrmNuevaCompra();
    frmnc.setVisible(true);

    
    JScrollPane scroll = new JScrollPane(frmnc,
    JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
    JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

    
    scroll.setPreferredSize(PanelFormularios.getSize());

    PanelFormularios.setLayout(new BorderLayout()); 
    PanelFormularios.add(scroll, BorderLayout.CENTER);

    PanelFormularios.revalidate();
    PanelFormularios.repaint();

        /*PanelFormularios.removeAll();
        PanelFormularios.repaint(); 
        FrmNuevaCompra frmnc = new FrmNuevaCompra();
        PanelFormularios.add(frmnc);
        frmnc.setVisible(true);*/
    }//GEN-LAST:event_MnNuevaCompraMouseClicked

    private void MnPosibleCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnPosibleCompraMouseClicked
        PanelFormularios.removeAll();
        PanelFormularios.repaint(); 
        FrmPosibleCompra frmpc = new FrmPosibleCompra();
        PanelFormularios.add(frmpc);
        frmpc.setVisible(true);
    }//GEN-LAST:event_MnPosibleCompraMouseClicked

    private void MnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnClientesMouseClicked
    PanelFormularios.removeAll();
    PanelFormularios.repaint(); 

    FrmCliente frmcl = new FrmCliente();
    frmcl.setVisible(true);

    
    JScrollPane scroll = new JScrollPane(frmcl,
        JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
        JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

    
    scroll.setPreferredSize(PanelFormularios.getSize());

    
    PanelFormularios.setLayout(new BorderLayout()); 
    PanelFormularios.add(scroll, BorderLayout.CENTER);

    PanelFormularios.revalidate();
    PanelFormularios.repaint();
    }//GEN-LAST:event_MnClientesMouseClicked

    private void MnCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnCreditosMouseClicked
    PanelFormularios.removeAll();
    PanelFormularios.repaint(); 

   
    FrmCredito frmcr = new FrmCredito();
    frmcr.setVisible(true);


    JScrollPane scroll = new JScrollPane(
        frmcr,
        JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
        JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED
    );

    
    scroll.setPreferredSize(PanelFormularios.getSize());

    
    PanelFormularios.setLayout(new BorderLayout()); 
    PanelFormularios.add(scroll, BorderLayout.CENTER);

    // Refresca el panel
    PanelFormularios.revalidate();
    PanelFormularios.repaint();
    }//GEN-LAST:event_MnCreditosMouseClicked

    private void MnImpuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnImpuestosMouseClicked
        PanelFormularios.removeAll();
        PanelFormularios.repaint(); 
        FrmImpuestos frmi = new FrmImpuestos();
        PanelFormularios.add(frmi);
        frmi.setVisible(true);
    }//GEN-LAST:event_MnImpuestosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPaginaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnClientes;
    private javax.swing.JMenu MnCompras;
    private javax.swing.JMenu MnComprobante;
    private javax.swing.JMenu MnCreditos;
    private javax.swing.JMenu MnExportar;
    private javax.swing.JMenu MnImpuestos;
    private javax.swing.JMenu MnMantenimiento;
    private javax.swing.JMenu MnNuevaCompra;
    private javax.swing.JMenu MnPosibleCompra;
    private javax.swing.JMenu MnReportes;
    private javax.swing.JMenu MnSalir;
    private javax.swing.JMenu MnTiendas;
    private javax.swing.JPanel PanelFormularios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
